version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test

  web:
    build: .
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: test